# Intake-ERDDAP

In [1]:
from intake_erddap.erddap_cat import ERDDAPCatalog
import intake

In [2]:
server = 'https://cioosatlantic.ca/erddap'
cat = ERDDAPCatalog(server)

In [3]:
list(cat)

['coastal_action_7471_9460_c025',
 'SMA_bay_of_exploits',
 'SMA_bay_of_islands',
 'bb1_bop_level1',
 'SMA_bonavista',
 'SMA_port_aux_basques',
 'SMA_port_aux_basqes_wharf',
 'coast-of-bays-hydrographic-2009-2013',
 'SMA_corner_brook_wharf',
 'SMA_saint_john_cruise_terminal',
 'SMA_Fortune_Bay_Buoy',
 'SMA_halifax',
 'SMA_halifax_fairview',
 'SMA_halifax_anemometer1',
 'SMA_halifax_pier9c',
 'SMA_head_of_placentia_bay-come_by_chance_point',
 'SMA_Holyrood_Buoy2',
 'SMA_holyrood_wharf',
 'SMA_bay_of_exploits_wharf',
 'SMA_manolis_buoy',
 'SMA_MouthofPlacentiaBayBuoy',
 'sma_negl_black_tickle_nlqu0003',
 'sma_negl_cartwright_junction_nlqu0004',
 'sma_negl_north_west_river_nlqu0007',
 'sma_negl_postville_nlqu0001',
 'sma_negl_red_bay_nlqu0005',
 'sma_negl_rigolet_nlqu0002',
 'SMA_red_island_shoal',
 'DFO_Sutron_NHARB',
 'DFO_Sutron_KLUMI',
 'SMA_saint_john_wharf',
 'SMA_saint_john',
 'SMA_st_johns',
 'SMA_st_johns_wharf',
 'SmartAtlantic_XEOS_hk4_buoy']

In [15]:
cat.SMA_bay_of_exploits.describe()

{'name': 'SMA_bay_of_exploits',
 'container': 'dataframe',
 'plugin': ['erddap'],
 'description': 'ERDDAP dataset_id SMA_bay_of_exploits from https://cioosatlantic.ca/erddap',
 'direct_access': True,
 'user_parameters': [],
 'metadata': {},
 'args': {'server': 'https://cioosatlantic.ca/erddap',
  'dataset_id': 'SMA_bay_of_exploits',
  'protocol': 'tabledap'}}

In [11]:
df = cat.SMA_manolis_buoy.read()

In [13]:
df.head()

,station_name,time (UTC),longitude (degrees_east),latitude (degrees_north),wind_spd_avg,wind_spd_max,wind_dir_avg,air_temp_avg,air_pressure_avg,air_humidity_avg,air_dewpoint_avg,surface_temp_avg,wave_ht_max,wave_ht_sig,wave_period_max,wave_dir_avg,wave_spread_avg,curr_dir_avg,curr_spd_avg
0,smb_manolis,2018-07-10T00:23:41Z,-54.507837,49.675302,5.9,7.2,222.0,18.9,1008.1,NaN,NaN,10.9,0.8,0.5,8.7,26.0,46.0,274.1,104.9
1,smb_manolis,2018-07-10T00:53:41Z,-54.507828,49.675285,4.8,6.1,218.0,18.4,1008.5,NaN,NaN,10.9,0.8,0.5,8.7,26.0,46.0,271.5,85.4
2,smb_manolis,2018-07-10T01:23:41Z,-54.507797,49.675293,7.8,9.9,235.0,19.8,1008.3,NaN,NaN,10.9,0.8,0.5,8.7,26.0,46.0,301.8,60.2
3,smb_manolis,2018-07-10T01:53:41Z,-54.507805,49.675285,7.8,9.7,237.0,19.1,1008.3,NaN,NaN,10.9,0.8,0.5,8.7,26.0,46.0,326.3,64.3
4,smb_manolis,2018-07-10T02:23:41Z,-54.507788,49.675310,6.9,7.6,233.0,17.3,1008.3,NaN,NaN,10.8,0.8,0.5,8.7,26.0,46.0,337.1,57.5